spring.application.name=controlzero-api
server.port=7070

spring.datasource.url=jdbc:mariadb://localhost:3307/controlzero-db
spring.datasource.username=controlzero-api
spring.datasource.password=control0
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

security.jwt.secret=replace-this-secret-with-at-least-32-characters
security.jwt.session-ttl-minutes=30
security.jwt.refresh-ttl-days=7
